[versions]
kotlin = "1.9.20"
compose = "1.5.11"
app="8.1.0"
activity-compose = "1.8.1"
moko-res = "0.23.0"
multiplatform-settings = "1.0.0"
koin = "3.4.0"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref="activity-compose"}
multiplatform-settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatform-settings" }
resources-core = { module = "dev.icerock.moko:resources", version.ref = "moko-res" }
resources-compose = { module = "dev.icerock.moko:resources-compose", version.ref = "moko-res" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin"}

[plugins]
compose = { id = "org.jetbrains.compose", version.ref = "compose"}
multiplatform = {id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin"}
android-application = { id = "com.android.application", version.ref = "app"}
android-library = { id = "com.android.library", version.ref = "app"}
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin"}
moko-res = { id = "dev.icerock.mobile.multiplatform-resources", version.ref = "moko-res"}